version: "3.9"

services:
  easy_gdb:
    build:
      context: .
    container_name: easy_gdb
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
  DB:
    image: postgres
    container_name: DB
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
